Add-PSSnapin Microsoft.SharePoint.PowerShell -erroraction SilentlyContinue
Get-SPDistributedCacheClientSetting -ContainerType DistributedDefaultCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedAccessCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedActivityFeedCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedBouncerCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedLogonTokenCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedServerToAppServerAccessTokenCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedSearchCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedSecurityTrimmingCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedActivityFeedLMTCache
Get-SPDistributedCacheClientSetting -ContainerType DistributedViewStateCache