gacutil -u Microsoft.Rtc.Collaboration.dll.
gacutil -u Microsoft.WindowsAzure.StorageClient.dll.
gacutil -u Microsoft.Xrm.Sdk.dll.
gacutil -u Nintex.Charting.dll.
gacutil -u Nintex.Utilities.Cab.dll.
gacutil -u Nintex.Workflow.AdministrationPages.dll.
gacutil -u Nintex.Workflow.Analytics.dll.
gacutil -u Nintex.Workflow.ApplicationPages.dll.
gacutil -u Nintex.Workflow.ConnectionManager.dll.
gacutil -u Nintex.Workflow.Features.dll.
gacutil -u Nintex.Workflow.Live.dll.
gacutil -u Nintex.Workflow.Maintenance.dll.
gacutil -u Nintex.Workflow.Resources.dll.
gacutil -u Nintex.Workflow.ServerControls.dll.
gacutil -u Nintex.Workflow.Start.dll.
gacutil -u Nintex.Workflow.SupportConsole.dll.
gacutil -u Nintex.Workflow.WebServices.dll.
gacutil -u Nintex.Workflow.dll.
gacutil -u microsoft.crm.sdk.dll.
gacutil -u microsoft.crm.sdktypeproxy.dll.
gacutil -u sipeps.dll.