name: Virus Total
on:
  push:
    paths:
      - Harden-Windows-Security Module/Main files/Resources/**
    # To filter by branches
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run Script
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Script
        env:
          VTAPIsecret: ${{ secrets.VTAPI }}
        shell: pwsh
        run: |

            ./.github/Workflowstuff/VirusTotal
