#region Application Functions
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 1/31/2011 1:04 PM
# Generated By: zachary.loeber
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$label4 = New-Object System.Windows.Forms.Label
$label3 = New-Object System.Windows.Forms.Label
$picboxAfter = New-Object System.Windows.Forms.PictureBox
$picboxBefore = New-Object System.Windows.Forms.PictureBox
$label2 = New-Object System.Windows.Forms.Label
$label1 = New-Object System.Windows.Forms.Label
$txtOutputFile = New-Object System.Windows.Forms.TextBox
$btnOutputFile = New-Object System.Windows.Forms.Button
$btnInputFile = New-Object System.Windows.Forms.Button
$txtInputFile = New-Object System.Windows.Forms.TextBox
$btnExit = New-Object System.Windows.Forms.Button
$btnConvert = New-Object System.Windows.Forms.Button
$openFileDialog1 = New-Object System.Windows.Forms.OpenFileDialog
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------

$btnOutputFile_OnClick= 
{
	try {
		if($openfiledialog1.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
			$txtOutputFile.Text = $openfiledialog1.FileName.ToString()
		}	
	}
	catch {
		[System.Windows.Forms.MessageBox]::Show(
		$_.Exception.Message,
		"Error",
		[System.Windows.Forms.MessageBoxButtons]::OK,
		[System.Windows.Forms.MessageBoxIcon]::Error
		)			
	}
}

$handler_txtInputFile_TextChanged= 
{
#TODO: Place custom script here

}

$btnConvert_OnClick= 
{
	if (($txtInputFile.Text -ne "") -and ($txtOutputFile.Text -ne "")) {
		C:\Scripts\convert.exe -quality 50 -depth 8 -strip -thumbnail 96x96^ -gravity Center -crop 96x96+0+0 $txtInputFile.Text $txtOutputFile.Text
		$picboxAfter.Image = [System.Drawing.Image]::FromFile($txtOutputFile.Text)
		$picboxAfter.Refresh()
	}
}

$btnInputFile_OnClick= 
{
	try {
		if($openfiledialog1.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
			$txtInputFile.Text = $openfiledialog1.FileName.ToString()
			$picboxBefore.Image = [System.Drawing.Image]::FromFile($openfiledialog1.FileName.ToString())
			$picboxBefore.Refresh()
		}	
	}
	catch {
		[System.Windows.Forms.MessageBox]::Show(
		$_.Exception.Message,
		"Error",
		[System.Windows.Forms.MessageBoxButtons]::OK,
		[System.Windows.Forms.MessageBoxIcon]::Error
		)			
	}
}

$handler_label2_Click= 
{
#TODO: Place custom script here

}

$handler_label1_Click= 
{
#TODO: Place custom script here

}

$handler_openFileDialog1_FileOk= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}


#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 250
$System_Drawing_Size.Width = 370
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.FormBorderStyle = 3
$form1.Name = "form1"
$form1.Text = "Convert Photo For Outlook"

$label4.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 250
$System_Drawing_Point.Y = 221
$label4.Location = $System_Drawing_Point
$label4.Name = "label4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 17
$System_Drawing_Size.Width = 87
$label4.Size = $System_Drawing_Size
$label4.TabIndex = 11
$label4.Text = "AFTER"
$label4.TextAlign = 32

$form1.Controls.Add($label4)

$label3.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 35
$System_Drawing_Point.Y = 218
$label3.Location = $System_Drawing_Point
$label3.Name = "label3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 92
$label3.Size = $System_Drawing_Size
$label3.TabIndex = 10
$label3.Text = "BEFORE"
$label3.TextAlign = 32

$form1.Controls.Add($label3)


$picboxAfter.BorderStyle = 1
$picboxAfter.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 227
$System_Drawing_Point.Y = 65
$picboxAfter.Location = $System_Drawing_Point
$picboxAfter.Name = "picboxAfter"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 150
$System_Drawing_Size.Width = 136
$picboxAfter.Size = $System_Drawing_Size
$picboxAfter.TabIndex = 9
$picboxAfter.TabStop = $False

$form1.Controls.Add($picboxAfter)


$picboxBefore.BorderStyle = 1
$picboxBefore.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 65
$picboxBefore.Location = $System_Drawing_Point
$picboxBefore.Name = "picboxBefore"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 150
$System_Drawing_Size.Width = 136
$picboxBefore.Size = $System_Drawing_Size
$picboxBefore.TabIndex = 8
$picboxBefore.TabStop = $False

$form1.Controls.Add($picboxBefore)

$label2.DataBindings.DefaultDataSourceUpdateMode = 0
$label2.Font = New-Object System.Drawing.Font("Arial",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = -4
$System_Drawing_Point.Y = 36
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 97
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 7
$label2.Text = "Output Picture:"
$label2.TextAlign = 1024
$label2.add_Click($handler_label2_Click)

$form1.Controls.Add($label2)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0
$label1.Font = New-Object System.Drawing.Font("Arial",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = -4
$System_Drawing_Point.Y = 10
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 97
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 6
$label1.Text = "Original Picture:"
$label1.TextAlign = 1024
$label1.add_Click($handler_label1_Click)

$form1.Controls.Add($label1)

$txtOutputFile.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 99
$System_Drawing_Point.Y = 37
$txtOutputFile.Location = $System_Drawing_Point
$txtOutputFile.Name = "txtOutputFile"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 235
$txtOutputFile.Size = $System_Drawing_Size
$txtOutputFile.TabIndex = 5

$form1.Controls.Add($txtOutputFile)


$btnOutputFile.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 339
$System_Drawing_Point.Y = 37
$btnOutputFile.Location = $System_Drawing_Point
$btnOutputFile.Name = "btnOutputFile"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 24
$btnOutputFile.Size = $System_Drawing_Size
$btnOutputFile.TabIndex = 4
$btnOutputFile.Text = "..."
$btnOutputFile.UseVisualStyleBackColor = $True
$btnOutputFile.add_Click($btnOutputFile_OnClick)

$form1.Controls.Add($btnOutputFile)


$btnInputFile.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 339
$System_Drawing_Point.Y = 11
$btnInputFile.Location = $System_Drawing_Point
$btnInputFile.Name = "btnInputFile"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 24
$btnInputFile.Size = $System_Drawing_Size
$btnInputFile.TabIndex = 3
$btnInputFile.Text = "..."
$btnInputFile.UseVisualStyleBackColor = $True
$btnInputFile.add_Click($btnInputFile_OnClick)

$form1.Controls.Add($btnInputFile)

$txtInputFile.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 99
$System_Drawing_Point.Y = 11
$txtInputFile.Location = $System_Drawing_Point
$txtInputFile.Name = "txtInputFile"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 235
$txtInputFile.Size = $System_Drawing_Size
$txtInputFile.TabIndex = 2
$txtInputFile.add_TextChanged($handler_txtInputFile_TextChanged)

$form1.Controls.Add($txtInputFile)


$btnExit.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 301
$System_Drawing_Point.Y = 269
$btnExit.Location = $System_Drawing_Point
$btnExit.Name = "btnExit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 62
$btnExit.Size = $System_Drawing_Size
$btnExit.TabIndex = 1
$btnExit.Text = "Exit"
$btnExit.UseVisualStyleBackColor = $True
$btnExit.add_Click($handler_button2_Click)

#$form1.Controls.Add($btnExit)


$btnConvert.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 155
$System_Drawing_Point.Y = 127
$btnConvert.Location = $System_Drawing_Point
$btnConvert.Name = "btnConvert"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 62
$btnConvert.Size = $System_Drawing_Size
$btnConvert.TabIndex = 0
$btnConvert.Text = "Convert!"
$btnConvert.UseVisualStyleBackColor = $True
$btnConvert.add_Click($btnConvert_OnClick)

$form1.Controls.Add($btnConvert)

$openFileDialog1.DefaultExt = ""
$openFileDialog1.Filter = "Image files (*.jpg,*.jpeg,*.bmp,*.tif,*.tiff,*.gif,*.png)|*.jpg;*.jpeg;*.bmp;*.tif;*.tiff;*.gif;*.png"
$openFileDialog1.InitialDirectory = "c:\"
$openFileDialog1.ShowHelp = $True
$openFileDialog1.ValidateNames = $False
$openFileDialog1.add_FileOk($handler_openFileDialog1_FileOk)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function
#endregion
#Call the Function
GenerateForm