$nulCipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL' -Name Enabled # value should be 0 (dword:00000000)
$Des_56_56Cipher= Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56' -Name Enabled # value should be 0 (dword:00000000)
$RC2_40_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 40/128' -Name Enabled # value should be 0 (dword:00000000)
$RC2_56_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 56/128' -Name Enabled # value should be 0 (dword:00000000)
$RC2_128_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 128/128' -Name Enabled # value should be 0 (dword:00000000)
$RC4_40_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128' -Name Enabled # value should be 0 (dword:00000000)
$RC4_56_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128' -Name Enabled # value should be 0 (dword:00000000)
$RC4_64_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 64/128' -Name Enabled # value should be 0 (dword:00000000)
$RC4_128_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128' -Name Enabled # value should be 0 (dword:00000000)
$Triple_DES_168Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168' -Name Enabled # value should be 0 (dword:00000000)
$AES_128_128Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128' -Name Enabled # value should be 4294967295 (dword:ffffffff)
$AES_256_256Cipher = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256' -Name Enabled # value should be 4294967295 (dword:ffffffff)

$MD5_Hash = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\MD5' -Name Enabled # value should be 0 (dword:00000000)
$SHA_HASH = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA' -Name Enabled # value should be 4294967295 (dword:ffffffff)
$SHA256_HASH = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA256' -Name Enabled # value should be 4294967295 (dword:ffffffff)
$SHA384_HASH = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA384' -Name Enabled # value should be 4294967295 (dword:ffffffff)
$SHA512_HASH = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA512' -Name Enabled # value should be 4294967295 (dword:ffffffff)

$DiffieHellman_KEA = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman' -Name Enabled # value should be 0 (dword:00000000)
$PKCS_KEA = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\PKCS' -Name Enabled # value should be 0 (dword:00000000)
$ECDH_KEA = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\ECDH' -Name Enabled # value should be 4294967295 (dword:ffffffff)

$MultiUnified_PROTOCOL = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\Multi-Protocol Unified Hello\Client' -Name Enabled # value should be 0 (dword:00000000)
$PCT1_PROTOCOL = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Client' -Name Enabled # value should be 0 (dword:00000000)
$SSL2_PROTOCOL = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client' -Name Enabled # value should be 0 (dword:00000000)
$SSL3_PROTOCOL = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client' -Name Enabled # value should be 0 (dword:00000000)
$TLS1_PROTOCOL = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -Name Enabled # value should be 0 (dword:00000000)
$TLS11_PROTOCOL = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -Name Enabled # value should be 0 (dword:00000000)
$TLS12_PROTOCOL = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client' -Name Enabled # value should be 0 (dword:00000000)
$MultiUnified_PROTOCOL_DBD = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\Multi-Protocol Unified Hello\Client' -Name DisabledByDefault # value should be 1 (dword:00000001)
$PCT1_PROTOCOL_DBD = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Client' -Name DisabledByDefault # value should be 1 (dword:00000001)
$SSL2_PROTOCOL_DBD = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client' -Name DisabledByDefault # value should be 1 (dword:00000001)
$SSL3_PROTOCOL_DBD = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client' -Name DisabledByDefault # value should be 1 (dword:00000001)
$TLS1_PROTOCOL_DBD = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client' -Name DisabledByDefault # value should be 1 (dword:00000001)
$TLS11_PROTOCOL_DBD = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client' -Name DisabledByDefault # value should be 1 (dword:00000001)
$TLS12_PROTOCOL_DBD = Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client' -Name DisabledByDefault # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client' -Name Enabled # value should be 1 (dword:00000001)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\Multi-Protocol Unified Hello\Server' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Server' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -Name Enabled # value should be 4294967295 (dword:ffffffff)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\Multi-Protocol Unified Hello\Server' -Name DisabledByDefault # value should be 1 (dword:00000001)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Server' -Name DisabledByDefault # value should be 1 (dword:00000001)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server' -Name DisabledByDefault # value should be 1 (dword:00000001)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server' -Name DisabledByDefault # value should be 1 (dword:00000001)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -Name DisabledByDefault # value should be 1 (dword:00000001)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server' -Name DisabledByDefault # value should be 1 (dword:00000001)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -Name DisabledByDefault # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman' -Name ServerMinKeyBitLength # value should be 2048 (dword:00000800)
Get-CRegistryKeyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy' -Name Enabled # value should be 0 (dword:00000000)
Get-CRegistryKeyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002' -Name Functions # value should be TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA



Get-TlsCipherSuite | foreach { $_.Name }
