start /WAIT cmd /c E:\Scripts\PHP_SCRIPTS\MU\start.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm01.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm01a.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm01b.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm02.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm03.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm04.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm05.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm07.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm07a.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm08.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm10.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm12.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm13.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm14.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm15.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\cm17.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\MO02.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\MO03.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\MO04.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS226.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS236.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS128.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS130.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS119.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS102.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS144.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS143.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS46.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS48.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS49.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS50.bat
start cmd /c E:\Scripts\PHP_SCRIPTS\MU\PQRS173.bat