Get-Service -Computername LASAUTH01.creditoneapp.biz, LASAUTH02.creditoneapp.biz -Name W3SVC
Get-Service -Computername LASSVC03 -Name CollectionsAgentTimeService,ContosoCheckRequestService,ContosoLPSService
Get-Service -Computername LASSVC04 -Name CentralizedCacheService,CreditOneBatchLetterRequestService,CreditOne.LogParser.Service,ContosoQueueProcessorService,CollectionsAgentTimeService,ContosoCheckRequestService,ContosoLPSService,fdrOutGoingFileWatcher,ValidationTriggerWatcher,ContosoFinCenService
Get-Service -Computername LASCASMT01 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT02 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT03 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT04 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT05 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT06 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT07 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT08 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT09 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCASMT10 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL01 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL02 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL03 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL04 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL05 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL06 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL07 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL08 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASCOLL09 -Name ContosoDataLayerService,W3SVC
Get-Service -Computername LASMT01 -Name ContosoDataLayerService
Get-Service -Computername LASMT02 -Name ContosoDataLayerService
Get-Service -Computername LASMT03 -Name ContosoDataLayerService
Get-Service -Computername LASMT04 -Name ContosoDataLayerService
Get-Service -Computername LASMT05 -Name ContosoDataLayerService
Get-Service -Computername LASMT06 -Name ContosoDataLayerService
Get-Service -Computername LASMT07 -Name ContosoDataLayerService
Get-Service -Computername LASMT08 -Name ContosoDataLayerService
Get-Service -Computername LASMT09 -Name ContosoDataLayerService
Get-Service -Computername LASMT10 -Name ContosoDataLayerService
Get-Service -Computername LASMCE01 -Name CreditEngine
Get-Service -Computername LASMCE02 -Name CreditEngine

Get-Service -Computername LASCAPSMT01 -Name CreditPullService,ContosoIPFraudCheckService,ContosoIdentityCheckService,ContosoApplicationProcessingService,ContosoApplicationImportService
Get-Service -Computername LASCAPSMT02 -Name CreditPullService,ContosoIPFraudCheckService,ContosoIdentityCheckService,ContosoApplicationProcessingService,ContosoDebitCardHolderFileWatcher,FromPPSExchangeFileWatcherService,ContosoApplicationImportService,ContosoApplicationParsingService
Get-Service -Computername LASCAPSMT05 -Name CreditPullService,ContosoIPFraudCheckService,ContosoIdentityCheckService,ContosoApplicationProcessingService,ContosoApplicationImportService
Get-Service -Computername LASCAPSMT06 -Name CreditPullService,ContosoIPFraudCheckService,ContosoIdentityCheckService,ContosoApplicationProcessingService,ContosoApplicationImportService
Get-Service -Computername LASCAPS01 -Name W3SVC
Get-Service -Computername LASCAPS02 -Name W3SVC
Get-Service -Computername LASCAPS05 -Name W3SVC
Get-Service -Computername LASCAPS06 -Name W3SVC
Get-Service -Computername LASCAS01 -Name W3SVC
Get-Service -Computername LASCAS02 -Name W3SVC
Get-Service -Computername LASCAS03 -Name W3SVC
Get-Service -Computername LASCAS04 -Name W3SVC
Get-Service -Computername LASCAS05 -Name W3SVC
Get-Service -Computername LASCAS06 -Name W3SVC
Get-Service -Computername LASCAS07 -Name W3SVC
Get-Service -Computername LASCAS08 -Name W3SVC
Get-Service -Computername LASCHAT01 -Name WhosOnGateway,WhosOnQuery,WhosOnReports,WhosOn,WhosOnServiceMonitor
Get-Service -Computername LASCHAT02 -Name WhosOnGateway,WhosOnQuery,WhosOnReports,WhosOn,WhosOnServiceMonitor
Get-Service -Computername LASPROCDB02 -Name MSSQLSERVER,SQLSERVERAGENT
Get-Service -Computername LASPROCAPP03 -Name P360PA-DOC_LINK,P360PA-WFSERVE,P360PA-WFSERVE2,P360PA-WFSERVEARCHIVE,P360PA-WFSERVEIMPORT
Get-Service -Computername LASPROCAPP04 -Name Service1
Get-Service -Computername LASRFAX01 -Name RFALERT,RFDB,RFDOCTRANS,RFEDCPARENTNOTIFY1,RFEDCCONV1,RFEDCFCOPY1,RFEDCGIMG1,RFEDCGENPCL1,RFEDCGTEXT1,RFEDCLOOKUP1,RFEDCMGR,RFEDCPARENTMON1,RFEDCRFSEND1,RFEDCRFSENDSTAT1,RFMIME,RFPAGE,RFQUEUE,RFRemote,RFRPC,RFSERVER,RFWORK1,RFWORK2,RFWORK3
Get-Service -Computername LASCODE02 -Name AccuRev Server,AccuRev DB Server,AccuRev RLM,JIRA050414101333
Get-Service -Computername LASITS01 -Name SQLANYs_sem5,SepMasterService,semsrv,semwebsrv,SmcService
Get-Service -Computername LASPRINT01 -Name Spooler
Get-Service -Computername LASINFRA01 -Name Schedule
