##################################
# Generated by Log Parser Studio #
##################################

#Name: IIS: Request per Hour
#Log Type: IISW3WC
#Generated: 2/15/2018 4:49:18 PM

Param(
    [parameter(Mandatory=$false)]
    [Bool]$AutoOpen,
	[parameter(Mandatory=$false)]
    [String]$OutFile,
	[parameter(Mandatory=$false)]
    [Bool]$IgnoreInParams,
	[parameter(Mandatory=$false)]
    [Bool]$IgnoreOutParams) 
	
$Error.Clear()
$DefaultFolder= "D:\Reports" #"C:\LazyWinAdmin\IIS" #[Environment]::GetFolderPath("MyDocuments")
$Destination = "IIS Request per Hour.CSV"
$Destination = $DefaultFolder + "\" + $Destination

if($OutFile -ne [String]::Empty)
{
	$OutFileType = [System.IO.Path]::GetExtension($OutFile.ToUpper())
	$OriginalFileType = [System.IO.Path]::GetExtension($Destination.ToUpper())
	if($OutFileType -ne $OriginalFileType)
	{
		Write-Host "You have chosen" $OutFileType "as the output, but this script was originally generated as" $OriginalFileType -ForegroundColor Red
		Write-Host "Either change -OutFile to" $OriginalFileType "or generate the script again with the output as" $OutFileType  -ForegroundColor Red
		Write-Host "You can also modify the OutputFormat variable in this script to match the correct Log Parser 2.2 COM output format." -ForegroundColor Red
		[System.Environment]::NewLine
		return
	}
	else
	{
		if($true -ne $OutFile.Contains("\"))
		{
		  $Destination = $DefaultFolder + "\" + $OutFile
		}
		else
		{
		  $Destination = $OutFile
		}
	}
}

$LogQuery = New-Object -ComObject "MSUtil.LogQuery"
$InputFormat = New-Object -ComObject "MSUtil.LogQuery.IISW3CInputFormat"
$OutputFormat = New-Object -ComObject "MSUtil.LogQuery.CSVOutputFormat"

if($IgnoreInParams-eq $false){
     $InputFormat.iCodePage=0
     $InputFormat.recurse=-1
     $InputFormat.minDateMod="1900-01-01 12:00:00"
     $InputFormat.dirTime=0
     $InputFormat.consolidateLogs=1
     $InputFormat.useDirectiveDateTime=0
     $InputFormat.useDoubleQuotes=0
}

if($IgnoreOutParams -eq $false){
     $OutputFormat.Headers="AUTO"
     $OutputFormat.oDQuotes="AUTO"
     $OutputFormat.tabs=0
     $OutputFormat.oTsFormat="yyyy-MM-dd hh:mm:ss"
     $OutputFormat.oCodepage=0
     $OutputFormat.fileMode=1
}
Write-Progress -Activity "Executing query, please wait..."  -Status " "

$SQLQuery = "SELECT QUANTIZE(TO_TIMESTAMP(date, time), 3600) AS Hour, COUNT(*) AS Total, SUM(sc-bytes) AS TotBytesSent  INTO '" + $Destination + "' FROM  '\\lasdmzweb01\D$\LogFiles\WebSites\*.log','\\lasdmzweb03\D$\LogFiles\WebSites\*.log','\\lasdmzweb01\D$\LogFiles\IIS\W3SVC2\*.log','\\lasdmzweb01\D$\LogFiles\IIS\W3SVC3\*.log','\\lasdmzweb01\D$\LogFiles\IIS\W3SVC5\*.log','\\lasdmzweb01\D$\LogFiles\IIS\W3SVC6\*.log','\\lasdmzweb01\D$\LogFiles\IIS\W3SVC7\*.log','\\lasdmzweb01\D$\LogFiles\IIS\W3SVC8\*.log','\\lasdmzweb01\D$\LogFiles\IIS\W3SVC9\*.log','\\lasdmzweb02\D$\LogFiles\IIS\W3SVC2\*.log','\\lasdmzweb02\D$\LogFiles\IIS\W3SVC3\*.log','\\lasdmzweb02\D$\LogFiles\IIS\W3SVC5\*.log','\\lasdmzweb02\D$\LogFiles\IIS\W3SVC6\*.log','\\lasdmzweb02\D$\LogFiles\IIS\W3SVC7\*.log','\\lasdmzweb02\D$\LogFiles\IIS\W3SVC8\*.log','\\lasdmzweb02\D$\LogFiles\IIS\W3SVC9\*.log','\\lasdmzweb03\D$\LogFiles\IIS\W3SVC5\*.log','\\lasdmzweb03\D$\LogFiles\IIS\W3SVC6\*.log','\\lasdmzweb03\D$\LogFiles\IIS\W3SVC7\*.log','\\lasdmzweb03\D$\LogFiles\IIS\W3SVC8\*.log','\\lasdmzweb03\D$\LogFiles\IIS\W3SVC9\*.log' GROUP BY Hour ORDER BY Hour "
$rtnVal = $LogQuery.ExecuteBatch($SQLQuery, $InputFormat, $OutputFormat);
$OutputFormat = $null;
$InputFormat = $null;
$LogQuery = $null;

if($AutoOpen)
{
	try
	{
		Start-Process($Destination)
	}
	catch
	{
		Write-Host $_.Exception.Message  -ForegroundColor Red
		Write-Host $_.Exception.GetType().FullName  -ForegroundColor Red
		Write-Host "NOTE: No output file will be created if the query returned zero records!"  -ForegroundColor Gray
	}	
}