git clone https://github.com/Appleseed/portal-stack
git clone https://github.com/aspnet/IISIntegration
git clone http://influx-capacitor.com/Home/Download
git clone https://github.com/Microsoft/IIS.WebManager
git clone https://github.com/unosquare/passcore
git clone https://github.com/fbprogmbh/Audit-Test-Automation
git clone https://github.com/mzd555/IISHealthMonitor
git clone https://github.com/akhmarov/f5_wmiperfmon
git clone https://github.com/opserver/Opserver
git clone https://github.com/jamesholcomb/InfluxDB.Net
git clone http://influx-capacitor.com
git clone https://github.com/adamdriscoll/PoshInternals
git clone https://github.com/SolidCore-IA/Powershell
git clone https://github.com/TheCjw/poshcfg
git clone https://github.com/AlexanderLebens/PoSH-Scripts
git clone https://github.com/giggio/poshfiles
git clone https://github.com/GooralLab/POSHReporting
git clone https://github.com/Nomango/posh-theme-PowerPrompt
git clone https://github.com/jkhy/F5_PoshAuto
git clone https://github.com/snipe/snipe-it