net use x: %2
cd %1
x:\setup.exe /ConfigurationFile=Rest.ini /INDICATEPROGRESS /IACCEPTSQLSERVERLICENSETERMS /Q /INSTANCENAME=%3 /AGTSVCPASSWORD=%4 /SQLSVCPASSWORD=%5 /FAILOVERCLUSTERGROUP=%6 /FAILOVERCLUSTERNETWORKNAME=%7
