net use x: %2
cd %1
x:\setup.exe /ConfigurationFile=First.ini /INDICATEPROGRESS /IACCEPTSQLSERVERLICENSETERMS /Q /INSTANCENAME=%3 /INSTANCEID=%3 /AGTSVCPASSWORD=%4 /SQLSVCPASSWORD=%5 /FAILOVERCLUSTERGROUP=%6 /FAILOVERCLUSTERNETWORKNAME=%7 /INSTALLSQLDATADIR=%8 /FAILOVERCLUSTERDISKS=%9
