@call init-path.cmd
echo Preparing optinals directory..

echo *****************************
MD %optdrv%%optpath%\Apps
MD %optdrv%%optpath%\Backup
MD %optdrv%%optpath%\Backup\Wins
MD %optdrv%%optpath%\Backup\Image
MD %optdrv%%optpath%\Backup\Dhcp
MD %optdrv%%optpath%\Backup\Dns
MD %optdrv%%optpath%\Backup\Printer
MD %optdrv%%optpath%\Backup\User
MD %optdrv%%optpath%\Backup\Share
MD %optdrv%%optpath%\Backup\SystemState
MD %optdrv%%optpath%\Driver
MD %optdrv%%optpath%\Driver\Network
MD %optdrv%%optpath%\Driver\Display
MD %optdrv%%optpath%\Driver\Monitor
MD %optdrv%%optpath%\Driver\Printer
MD %optdrv%%optpath%\Driver\Modem
MD %optdrv%%optpath%\Driver\Storage
MD %optdrv%%optpath%\Driver\TapeDrv
MD %optdrv%%optpath%\Driver\Audio
MD %optdrv%%optpath%\Driver\Firmware
MD %optdrv%%optpath%\Driver\ChipSet
MD %optdrv%%optpath%\Os
MD %optdrv%%optpath%\Script
MD %optdrv%%optpath%\Toolkit
MD %optdrv%%optpath%\Update
echo *****************************