icacls \\fnbmcorp\procfiles\Dev01 /save DFS_Procfiles_Dev01.txt /T /C
icacls \\fnbmcorp\procfiles\FDR_CCycle /save DFS_Procfiles_FDR_CCycle.txt /T /C 
icacls \\fnbmcorp\procfiles\FDR_MCycle /save DFS_Procfiles_MCycle.txt /T /C
icacls \\fnbmcorp\procfiles\HF01 /save DFS_Procfiles_HF01.txt /T /C
icacls \\fnbmcorp\procfiles\Pdev01 /save DFS_Procfiles_Pdev01.txt /T /C
icacls \\fnbmcorp\procfiles\Prod /save DFS_Procfiles_Prod.txt /T /C
icacls \\fnbmcorp\procfiles\RL01 /save DFS_Procfiles_RL01.txt /T /C
icacls \\fnbmcorp\procfiles\STG01 /save DFS_Procfiles_STG01.txt /T /C
icacls \\fnbmcorp\procfiles\Test01 /save DFS_Procfiles_Test01.txt /T /C
icacls \\fnbmcorp\procfiles\Test02 /save DFS_Procfiles_Test02.txt /T /C
icacls \\fnbmcorp\procfiles\Test03 /save DFS_Procfiles_Test03.txt /T /C
icacls \\fnbmcorp\procfiles\Test04 /save DFS_Procfiles_Test04.txt /T /C
icacls \\fnbmcorp\procfiles\Test05 /save DFS_Procfiles_Test05.txt /T /C
icacls \\fnbmcorp\procfiles\Test06 /save DFS_Procfiles_Test06.txt /T /C
icacls \\fnbmcorp\procfiles\Trn01 /save DFS_Procfiles_Trn01.txt /T /C